import { useState, useRef, useEffect } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  Sparkles, Youtube, Newspaper, Globe, ChevronLeft,
  ChevronRight, ExternalLink, BookOpen, Brain, Bookmark, Check
} from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { saveTopic } from '../hooks/useFirebase';
import { explainTopic } from '../services/aiService';
import './TopicResults.css';

const REELS = [
  { id: 1, thumb: 'https://images.unsplash.com/photo-1677442135703-1787eea5ce01?w=400&q=80', title: '60s AI Explainer', views: '1.2M' },
  { id: 2, thumb: 'https://images.unsplash.com/photo-1636466497217-26a8cbeaf0aa?w=400&q=80', title: 'Quick Science', views: '943K' },
  { id: 3, thumb: 'https://images.unsplash.com/photo-1462332420958-a05d1e002413?w=400&q=80', title: 'Space in 90s', views: '2.1M' },
  { id: 4, thumb: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=400&q=80', title: 'Mind & Matter', views: '678K' },
  { id: 5, thumb: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=400&q=80', title: 'Future Tech', views: '3.4M' },
];

const ARTICLES = [
  { title: 'How Neural Networks Changed Everything', source: 'MIT Technology Review', time: '12 min read', image: 'https://images.unsplash.com/photo-1620712943543-bcc4688e7485?w=120&q=80' },
  { title: 'The Ethics of Artificial Intelligence', source: 'Nature', time: '8 min read', image: 'https://images.unsplash.com/photo-1655720031554-a929595ffad7?w=120&q=80' },
  { title: 'Understanding Large Language Models', source: 'Wired', time: '15 min read', image: 'https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=120&q=80' },
];

const SITES = [
  { name: 'Wikipedia', url: 'wikipedia.org', desc: 'Comprehensive overview and history', color: '#3b82f6' },
  { name: 'Stanford AI Lab', url: 'ai.stanford.edu', desc: 'Academic research and papers', color: '#ef4444' },
  { name: 'Towards Data Science', url: 'towardsdatascience.com', desc: 'Tutorials and explainers', color: '#10b981' },
];

export default function TopicResults() {
  const { slug } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const topic = slug.replace(/-/g, ' ');
  const reelsRef = useRef(null);
  const [topicSaved, setTopicSaved] = useState(false);
  const [saving, setSaving] = useState(false);
  const [explanation, setExplanation] = useState('');
  const [loadingAi, setLoadingAi] = useState(true);

  useEffect(() => {
    async function fetchExplanation() {
      try {
        setLoadingAi(true);
        const text = await explainTopic(topic);
        setExplanation(text);
      } catch (err) {
        setExplanation('Failed to load AI explanation. Please check your connection or try again later.');
        console.error(err);
      } finally {
        setLoadingAi(false);
      }
    }
    fetchExplanation();
  }, [topic]);

  async function handleSaveTopic() {
    if (!user || topicSaved) return;
    setSaving(true);
    try {
      await saveTopic(user.uid, topic.charAt(0).toUpperCase() + topic.slice(1), 'General', `Explore: ${topic}`);
      setTopicSaved(true);
    } finally {
      setSaving(false);
    }
  }

  function scrollReels(dir) {
    reelsRef.current?.scrollBy({ left: dir * 200, behavior: 'smooth' });
  }

  return (
    <div className="topic-page">
      {/* Header */}
      <div className="topic-header">
        <button className="btn btn-ghost" style={{ gap: 6, paddingLeft: 12 }} onClick={() => navigate(-1)}>
          <ChevronLeft size={18} /> Back
        </button>
        <div className="topic-header__info">
          <h1 className="topic-header__title font-display text-gradient">{topic}</h1>
          <span className="badge badge-primary">Exploring</span>
        </div>
        <button
          className={`btn ${topicSaved ? 'btn-ghost' : 'btn-primary'}`}
          style={{ marginLeft: 'auto', gap: 6, fontSize: 13, padding: '8px 16px' }}
          onClick={handleSaveTopic}
          disabled={saving || topicSaved}
          id="save-topic-btn"
        >
          {topicSaved ? <><Check size={14} /> Saved</> : <><Bookmark size={14} /> Save Topic</>}
        </button>
      </div>

      {/* AI Explanation Card */}
      <section className="topic-section animate-fadeIn">
        <div className="ai-card glass-card">
          <div className="ai-card__header">
            <div className="ai-card__icon">
              <Brain size={20} fill="rgba(167,139,250,0.3)" />
            </div>
            <div>
              <h2 className="font-semibold" style={{ fontSize: 16 }}>AI Summary</h2>
              <p className="text-muted text-xs">Generated by Lexora AI</p>
            </div>
            <span className="badge badge-cyan" style={{ marginLeft: 'auto' }}>
              <Sparkles size={10} style={{ marginRight: 4 }} />AI
            </span>
          </div>
          <p className="ai-card__text">
            <strong style={{ color: 'var(--text-primary)', textTransform: 'capitalize' }}>{topic}</strong> is
            a transformative field that has reshaped how we understand the modern world. At its core, it explores
            the interplay between complex systems, emergent behavior, and human understanding. Research in this
            domain has accelerated rapidly, yielding breakthroughs that touch on perception, memory, decision-making,
            and the nature of intelligence itself. From foundational theories to cutting-edge applications, the study
            of {topic.toLowerCase()} continues to unlock new possibilities in science, society, and everyday life.
          </p>
          <div className="ai-card__meta">
            <span className="text-muted text-xs">Sources: 2,400+ academic papers · Updated today</span>
          </div>
        </div>
      </section>

      {/* YouTube Video */}
      <section className="topic-section animate-fadeIn" style={{ animationDelay: '0.1s' }}>
        <div className="section-header">
          <Youtube size={20} style={{ color: '#f43f5e' }} />
          <h2 className="font-semibold">Top Video</h2>
        </div>
        <div className="youtube-embed glass-card" style={{ padding: 0 }}>
          <div className="youtube-thumb">
            <img
              src="https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=900&q=80"
              alt={`Video about ${topic}`}
            />
            <div className="youtube-overlay">
              <div className="yt-play-btn">
                <Youtube size={36} fill="white" color="transparent" />
              </div>
              <div className="yt-meta">
                <p className="font-semibold" style={{ fontSize: 17, color: 'white' }}>
                  The Complete Guide to {topic.charAt(0).toUpperCase() + topic.slice(1)} – 2026 Edition
                </p>
                <p style={{ color: 'rgba(255,255,255,0.7)', fontSize: 13 }}>Lexora Picks · 48 min · HD</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Reels Slider */}
      <section className="topic-section animate-fadeIn" style={{ animationDelay: '0.15s' }}>
        <div className="section-header">
          <BookOpen size={20} style={{ color: 'var(--secondary)' }} />
          <h2 className="font-semibold">Short Clips</h2>
          <div style={{ marginLeft: 'auto', display: 'flex', gap: 8 }}>
            <button className="btn-icon" onClick={() => scrollReels(-1)}><ChevronLeft size={18} /></button>
            <button className="btn-icon" onClick={() => scrollReels(1)}><ChevronRight size={18} /></button>
          </div>
        </div>
        <div className="reels-slider" ref={reelsRef}>
          {REELS.map(reel => (
            <div key={reel.id} className="reel-card">
              <div className="reel-card__thumb">
                <img src={reel.thumb} alt={reel.title} />
                <div className="reel-card__overlay" />
                <div className="reel-card__info">
                  <p className="reel-card__title">{reel.title}</p>
                  <p className="reel-card__views text-xs">{reel.views} views</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Articles */}
      <section className="topic-section animate-fadeIn" style={{ animationDelay: '0.2s' }}>
        <div className="section-header">
          <Newspaper size={20} style={{ color: 'var(--accent)' }} />
          <h2 className="font-semibold">Articles</h2>
        </div>
        <div className="articles-list">
          {ARTICLES.map(a => (
            <div key={a.title} className="article-item glass-card">
              <img src={a.image} alt={a.title} className="article-item__img" />
              <div className="article-item__content">
                <h3 className="article-item__title">{a.title}</h3>
                <div className="flex items-center gap-3 mt-3">
                  <span className="badge badge-cyan">{a.source}</span>
                  <span className="text-muted text-xs">{a.time}</span>
                </div>
              </div>
              <ExternalLink size={16} style={{ color: 'var(--text-muted)', flexShrink: 0, marginTop: 4 }} />
            </div>
          ))}
        </div>
      </section>

      {/* Related Websites */}
      <section className="topic-section animate-fadeIn" style={{ animationDelay: '0.25s' }}>
        <div className="section-header">
          <Globe size={20} style={{ color: 'var(--primary-light)' }} />
          <h2 className="font-semibold">Related Websites</h2>
        </div>
        <div className="websites-grid">
          {SITES.map(site => (
            <div key={site.name} className="site-card glass-card">
              <div className="site-card__dot" style={{ background: site.color }} />
              <div>
                <p className="font-semibold" style={{ fontSize: 15 }}>{site.name}</p>
                <p className="text-muted text-sm">{site.url}</p>
                <p className="text-secondary text-sm mt-1">{site.desc}</p>
              </div>
              <ExternalLink size={16} style={{ color: 'var(--text-muted)', marginLeft: 'auto', flexShrink: 0 }} />
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
